const refs = {
  backdrop: document.querySelector('.backdrop'),
  teamLink: document.querySelector('.js-team'),
  spinerBackdrop: document.querySelector('.spiner__backdrop'),
  filmsListRef: document.querySelector('.films'),
  gallery: document.querySelector('.gallery__set'),
  libGallery: document.querySelector('.lib-gallery__set'),
  container: document.getElementById('pagination'),
  galleryGenreItem: document.querySelector('.film__genres'),
  form: document.querySelector('.header-film__form'),
  closeModalBtnForOneMovie: document.querySelector('.modal__button'),
  modalForOneMovie: document.querySelector('.modal'),
  backdropOneMovie: document.querySelector('.backdrop'),
  btnAddToWatched: document.querySelector('.btn__modal-add'),
  btnRemoveFromWatched: document.querySelector('.btn__modal-r-watched'),
  btnAddToQuene: document.querySelector('.btn__modal-queue'),
  btnRemoveFromQuene: document.querySelector('.btn__modal-r-queue'),
  trailerBackdrop: document.querySelector('.js-backdrop-trailer'),
  checkBox: document.querySelector('.checkbox'),
  main: document.querySelector('main'),
  footer: document.querySelector('footer'),
  footerText: document.querySelector('.footer__txt'),
  footerTextP: document.querySelector('.footer__txt-p'),
  footerTextBtn: document.querySelector('.footer__txt-btn'),
  footerTextPP: document.querySelector('.footer__txt-p-p'),
  globalInputValue: '',
};

export { refs };
